### ISSUE TITLE
ReportBAD/ReportGOOD

### ISSUE THREAD

**Issue by ghost** [jumper423/decaptcha#10]
https://rucaptcha.com/blog/reportbad-reportgood
Планируется ли реализация?

**Comment by jumper423** [comment]
@Aliaxander оно уже работает.
https://github.com/jumper423/decaptcha/blob/5a182fe1e00d2082bfb6debc3c90d0c7e72cfe30/src/services/RuCaptcha.php#L366
Необходимо использовать методы ->notTrue() или ->true()

Вопрос можно закрывать?

**Comment by jumper423** [comment]
Закрываю вопрос.

**Comment by ghost** [comment]
+. Спасибо.
